services:

  db:
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defaultdb
    restart: always

  adminer:
    image: adminer
    ports:
      - 8180:8080
    restart: always
