server:
  error:
    include-stacktrace: never

spring:
  r2dbc:
    url: r2dbc:postgres://localhost:5432/defaultdb
    username: postgres
    password: postgres

r2dbc:
  migrate:
    resources-paths:
      - classpath:/db/migration/*.sql
