name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
# TODO Tests aren't working with Github Actions for some reason, but run fine locally
#  run-unit-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#      - name: Install Java
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#          cache: 'gradle'
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v3
#      - name: Run unit tests
#        run: |
#          ./gradlew test

  check-compliance:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: defaultdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
      - name: k6 Compliance
        run: |
          ./gradlew bootRun &
          sleep 30s
          ./k6 run -e PORT=8080 https://raw.githubusercontent.com/weesvc/workbench/main/scripts/api-compliance.js
